# Generated by Django 3.2.21 on 2023-09-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230908_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
