# Generated by Django 3.2.21 on 2023-09-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230914_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
