# Generated by Django 3.2.21 on 2023-09-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230914_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='last_login',
        ),
    ]
