# Generated by Django 3.2.21 on 2023-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230914_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
