# Generated by Django 3.2.21 on 2023-09-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230914_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
