# Generated by Django 3.2.21 on 2023-09-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
